package Vista;

import Modelo.Carga;
import Modelo.Grafo;
import Modelo.Nodo;
import java.awt.Graphics;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.PointerInfo;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import javax.swing.ImageIcon;

/**
 * Proyecto Sistemas Inteligentes I Clase Main Clase Principal de la interfaz
 * grafica
 *
 * @author Diego Alejandro Parra Medina
 * @author Juan Bernardo Henao Orozco Universidad de Caldas, 2023-1 Universidad
 * de Caldas, 2023-1
 * @version 0.1
 */
public class Principal extends javax.swing.JFrame{

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAlgoritmo = new javax.swing.JLabel();
        jComboBoxAlgoritmo = new javax.swing.JComboBox<>();
        jLabelHeuristica = new javax.swing.JLabel();
        jComboBoxHeuristica = new javax.swing.JComboBox<>();
        jButtonConfirmaAlgoritmo = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonCargarMapa = new javax.swing.JButton();
        jButtonNuevoMapa = new javax.swing.JButton();
        jLabelEditarMapa = new javax.swing.JLabel();
        jButtonCamino = new javax.swing.JButton();
        jButtonRocas = new javax.swing.JButton();
        jButtonMetal = new javax.swing.JButton();
        jButtonBomberMan = new javax.swing.JButton();
        jButtonPuerta = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BOMBERMAN");
        setBackground(new java.awt.Color(153, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(260, 20));
        setPreferredSize(new java.awt.Dimension(790, 665));
        setResizable(false);

        jLabelAlgoritmo.setText("Algoritmo:");

        jComboBoxAlgoritmo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anchura", "Profundidad", "Costo Uniforme", "Beam Search", "Hill Climbing", "A Estrella" }));
        jComboBoxAlgoritmo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAlgoritmoActionPerformed(evt);
            }
        });

        jLabelHeuristica.setText("Heurística:");

        jComboBoxHeuristica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manhattan", "Euclidiana" }));

        jButtonConfirmaAlgoritmo.setText(">>>");
        jButtonConfirmaAlgoritmo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmaAlgoritmoActionPerformed(evt);
            }
        });

        jButtonLimpiar.setText("X");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });

        jButtonCargarMapa.setText("Cargar Mapa");
        jButtonCargarMapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargarMapaActionPerformed(evt);
            }
        });

        jButtonNuevoMapa.setText("Nuevo Mapa");
        jButtonNuevoMapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoMapaActionPerformed(evt);
            }
        });

        jLabelEditarMapa.setText("Editar Mapa");

        jButtonCamino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/ImagenCamino.jpg"))); // NOI18N
        jButtonCamino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCaminoActionPerformed(evt);
            }
        });

        jButtonRocas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/ImagenRocas.jpg"))); // NOI18N
        jButtonRocas.setToolTipText("");
        jButtonRocas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRocasActionPerformed(evt);
            }
        });

        jButtonMetal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/ImagenMetal.jpg"))); // NOI18N
        jButtonMetal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMetalActionPerformed(evt);
            }
        });

        jButtonBomberMan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/ImagenBomberMan.jpg"))); // NOI18N
        jButtonBomberMan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBomberManActionPerformed(evt);
            }
        });

        jButtonPuerta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/ImagenPuerta.jpg"))); // NOI18N
        jButtonPuerta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPuertaActionPerformed(evt);
            }
        });

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabelAlgoritmo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxAlgoritmo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabelHeuristica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxHeuristica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonConfirmaAlgoritmo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButtonLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonCargarMapa, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(jButtonNuevoMapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelEditarMapa)
                                .addGap(50, 50, 50))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonPuerta)
                                    .addComponent(jButtonBomberMan)
                                    .addComponent(jButtonRocas)
                                    .addComponent(jButtonCamino)
                                    .addComponent(jButtonMetal))
                                .addGap(29, 29, 29))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxAlgoritmo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelAlgoritmo)
                        .addComponent(jLabelHeuristica)
                        .addComponent(jComboBoxHeuristica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonConfirmaAlgoritmo)
                        .addComponent(jButtonLimpiar))
                    .addComponent(jButtonCargarMapa, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNuevoMapa)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabelEditarMapa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCamino))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRocas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonMetal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonBomberMan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonPuerta)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private Grafo grafo;
    private int m;
    private int n;
    private int tamano;
    private String inicio;
    private String salida;
    private List<Nodo> listaVisitados = new ArrayList<>();
    private String seleccionado;
    private int posXMouse;
    private int posYMouse;
    private ImageIcon imagenMetal = new ImageIcon(getClass().getResource("Imagenes/ImagenMetal.jpg"));
    private ImageIcon imagenRocas = new ImageIcon(getClass().getResource("Imagenes/ImagenRocas.jpg"));
    private ImageIcon imagenCamino = new ImageIcon(getClass().getResource("Imagenes/ImagenCamino.jpg"));
    private ImageIcon imagenBomberMan = new ImageIcon(getClass().getResource("Imagenes/ImagenBomberMan.jpg"));

    @Override
    public void paint(Graphics g) {
        super.paint(g);

        if (grafo != null) {
            //Pintar mapa
            for (Nodo nodo : grafo.getTablaAdyacencia()) {
                if (nodo.getEstado().equals("C")) {
                    g.drawImage(imagenCamino.getImage(), (nodo.getCoordenadaX() * tamano) + 13, (nodo.getCoordenadaY() * tamano) + 81, tamano, tamano, this);
                } else if (nodo.getEstado().equals("M")) {
                    g.drawImage(imagenMetal.getImage(), (nodo.getCoordenadaX() * tamano) + 13, (nodo.getCoordenadaY() * tamano) + 81, tamano, tamano, this);
                } else if (nodo.getEstado().equals("R")) {
                    g.drawImage(imagenRocas.getImage(), (nodo.getCoordenadaX() * tamano) + 13, (nodo.getCoordenadaY() * tamano) + 81, tamano, tamano, this);
                }
                if (!listaVisitados.isEmpty()) {
                    for (Nodo nodoVisitado : listaVisitados) {
                        g.drawString("" + listaVisitados.indexOf(nodoVisitado), (nodoVisitado.getCoordenadaX() * tamano) + 15, (nodoVisitado.getCoordenadaY() * tamano) + 93);
                    }
                }
            }
        }
    }

    private void jButtonCargarMapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargarMapaActionPerformed
        Carga carga = new Carga();
        grafo = carga.cargarTXT();

        n = carga.calculoN(); //Calculo N -> x
        m = carga.calculoM(); //Calculo M -> y
        tamano = 570 / Math.max(n, m);

        repaint(); //Pinta el mapa

        /*
        //Pedimos el nodo inicio y salida del grafo
        Scanner entradaEscaner = new Scanner(System.in);
        String entradaInicio = ""; //id del nodo inicio
        String entradaSalida = ""; //id del nodo salida

        do {
            System.out.println("Id del nodo inicio: ");
            entradaInicio = entradaEscaner.nextLine(); //0,0
        } while (grafo.numNodo(entradaInicio) < 0 && !"C".equals(grafo.getTablaAdyacencia()[grafo.numNodo(entradaInicio)].getEstado()));

        do {
            System.out.println("Id del nodo salida: "); //6,2
            entradaSalida = entradaEscaner.nextLine();
        } while (grafo.numNodo(entradaSalida) < 0 && !"C".equals(grafo.getTablaAdyacencia()[grafo.numNodo(entradaSalida)].getEstado()));
         */
        inicio = "0,0";
        salida = "6,2";

        grafo.setInicio(grafo.getTablaAdyacencia()[grafo.numNodo(inicio)]);
        grafo.setSalida(grafo.getTablaAdyacencia()[grafo.numNodo(salida)]);
    }//GEN-LAST:event_jButtonCargarMapaActionPerformed

    private void jButtonNuevoMapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoMapaActionPerformed
        listaVisitados.clear();
        grafo = null;
        repaint();
    }//GEN-LAST:event_jButtonNuevoMapaActionPerformed

    private void jComboBoxAlgoritmoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAlgoritmoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxAlgoritmoActionPerformed

    private void jButtonConfirmaAlgoritmoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmaAlgoritmoActionPerformed
        String algoritmo = jComboBoxAlgoritmo.getSelectedItem().toString();
        String heuristica = jComboBoxHeuristica.getSelectedItem().toString();

        if (grafo != null) {
            if (algoritmo.equals("Anchura")) {
                System.out.println("* * * Anchura * * *");
                listaVisitados = grafo.anchura(grafo.getTablaAdyacencia()[grafo.numNodo(inicio)], grafo.getTablaAdyacencia()[grafo.numNodo(salida)]);
            } else if (algoritmo.equals("Profundidad")) {
                System.out.println("* * * Profundidad * * *");
                listaVisitados = grafo.profundidad(grafo.getTablaAdyacencia()[grafo.numNodo(inicio)], grafo.getTablaAdyacencia()[grafo.numNodo(salida)], listaVisitados);
            } else if (algoritmo.equals("Costo Uniforme")) {
                System.out.println("* * * Costo Uniforme * * *");
                listaVisitados = grafo.costoUniforme(grafo.getTablaAdyacencia()[grafo.numNodo(inicio)], grafo.getTablaAdyacencia()[grafo.numNodo(salida)]);
            } else {
                if (heuristica.equals("Manhattan")) {
                    if (algoritmo.equals("Beam Search")) {
                        System.out.println("* * * Beam Search * * *");
                        System.out.println("Heurística: Manhattan");
                        listaVisitados = grafo.beamSearch(grafo.getTablaAdyacencia()[grafo.numNodo(inicio)], grafo.getTablaAdyacencia()[grafo.numNodo(salida)], "1");
                    } else if (algoritmo.equals("Hill Climbing")) {
                        System.out.println("* * * Hill Climbing * * *");
                        System.out.println("Heurística: Manhattan");
                        listaVisitados = grafo.hillClimbing(grafo.getTablaAdyacencia()[grafo.numNodo(inicio)], grafo.getTablaAdyacencia()[grafo.numNodo(salida)], "1");
                    } else if (algoritmo.equals("A Estrella")) {
                        System.out.println("* * * A Estrella * * *");
                        System.out.println("Heurística: Manhattan");
                        listaVisitados = grafo.aEstrella(grafo.getTablaAdyacencia()[grafo.numNodo(inicio)], grafo.getTablaAdyacencia()[grafo.numNodo(salida)], "1");
                    }
                } else if (heuristica.equals("Euclidiana")) {
                    if (algoritmo.equals("Beam Search")) {
                        System.out.println("* * * Beam Search * * *");
                        System.out.println("Heurística: Euclidiana");
                        listaVisitados = grafo.beamSearch(grafo.getTablaAdyacencia()[grafo.numNodo(inicio)], grafo.getTablaAdyacencia()[grafo.numNodo(salida)], "2");
                    } else if (algoritmo.equals("Hill Climbing")) {
                        System.out.println("* * * Hill Climbing * * *");
                        System.out.println("Heurística: Euclidiana");
                        listaVisitados = grafo.hillClimbing(grafo.getTablaAdyacencia()[grafo.numNodo(inicio)], grafo.getTablaAdyacencia()[grafo.numNodo(salida)], "2");
                    } else if (algoritmo.equals("A Estrella")) {
                        System.out.println("* * * A Estrella * * *");
                        System.out.println("Heurística: Euclidiana");
                        listaVisitados = grafo.aEstrella(grafo.getTablaAdyacencia()[grafo.numNodo(inicio)], grafo.getTablaAdyacencia()[grafo.numNodo(salida)], "2");
                    }
                }
            }
            grafo.imprimirRecorrido(listaVisitados);
            repaint(); //Pinta el mapa
        }
    }//GEN-LAST:event_jButtonConfirmaAlgoritmoActionPerformed

    private void jButtonCaminoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCaminoActionPerformed
        seleccionado = "C";
        listaVisitados.clear();
        repaint();
    }//GEN-LAST:event_jButtonCaminoActionPerformed

    private void jButtonRocasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRocasActionPerformed
        seleccionado = "R";
        listaVisitados.clear();
        repaint();
    }//GEN-LAST:event_jButtonRocasActionPerformed

    private void jButtonMetalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMetalActionPerformed
        seleccionado = "M";
        listaVisitados.clear();
        repaint();
    }//GEN-LAST:event_jButtonMetalActionPerformed

    private void jButtonBomberManActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBomberManActionPerformed
        seleccionado = "Inicio";
        listaVisitados.clear();
        repaint();
    }//GEN-LAST:event_jButtonBomberManActionPerformed

    private void jButtonPuertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPuertaActionPerformed
        seleccionado = "Salida";
        listaVisitados.clear();
        repaint();
    }//GEN-LAST:event_jButtonPuertaActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        listaVisitados.clear();
        repaint();
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        PointerInfo pi = MouseInfo.getPointerInfo();
        Point p = pi.getLocation();
        posXMouse = (int) p.getX();
        posYMouse = (int) p.getY();
        System.out.println(posXMouse + " - " + posYMouse);
    }//GEN-LAST:event_jPanel1MousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBomberMan;
    private javax.swing.JButton jButtonCamino;
    private javax.swing.JButton jButtonCargarMapa;
    private javax.swing.JButton jButtonConfirmaAlgoritmo;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonMetal;
    private javax.swing.JButton jButtonNuevoMapa;
    private javax.swing.JButton jButtonPuerta;
    private javax.swing.JButton jButtonRocas;
    private javax.swing.JComboBox<String> jComboBoxAlgoritmo;
    private javax.swing.JComboBox<String> jComboBoxHeuristica;
    private javax.swing.JLabel jLabelAlgoritmo;
    private javax.swing.JLabel jLabelEditarMapa;
    private javax.swing.JLabel jLabelHeuristica;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
